### ISSUE TITLE
GET request to BatchRefine transformer goes wrong

### ISSUE THREAD

**Issue by ktk** [fusepoolP3/p3-proxy#12]
While debugging https://github.com/fusepoolP3/p3-dashboard/issues/10 we noticed that the request to BatchRefine seems to be wrong. A correct request should look similar to this:

```
GET /?refinejson=http%3A%2F%2Fsandbox.fusepool.info%3A8181%2Fldp%2Fbla-json.json HTTP/1.1
Accept: text/turtle
Host: sandbox.fusepool.info:8310
```
while we see it executing:

```
GET ?refinejson=http%3A%2F%2Fsandbox.fusepool.info%3A8181%2Fldp%2Fbla-json.json HTTP/1.1
Accept: text/turtle
Host: sandbox.fusepool.info:8310
```
So there is a `/`missing before the query parameters.

**Comment by retog** [comment]
Im seeing

```
GET /?refinejson=http%3A%2F%2Fsandbox.fusepool.info%3A8181%2Fldp%2Fbla-json.json HTTP/1.1
```

wehn testing the client library.  I'm using java 8, so maybe the problem is related to an older java version, will check with the version in reference implementation docker.

**Comment by retog** [comment]
The problem doesn't occur when using java 8. Will update reference implementation docker.
