### ISSUE TITLE
T-LDPC does not convert files

### ISSUE THREAD

**Issue by ktk** [fusepoolP3/p3-proxy#13]
I created a new T-LDPC using the dashboard on playground.fusepool.info. I still have an issue with the URI created from the pipeline UI (https://github.com/fusepoolP3/p3-pipeline-gui/issues/8) so I add the correct URI manually which leads to this TLDP-C:

    http://playground.fusepool.info:8181/ldp/dcr/default-configuration/ALOD-BAR-Neu

If I now post a file there via Dashboard UI or via curl I see the CSV-File ending up there. But it never seems to be transformed.

Note that I am using the sandbox UI to make sure I'm on the latest UI code (http://sandbox.fusepool.info:8200/index.html?platformURI=http://playground.fusepool.info/)

**Comment by ktk** [comment]
It seems that @danilogiacomi reported a similar issue to @retog end of December

**Comment by ktk** [comment]
Forgot to mention that posting the file directly to the transformer works fine:

    curl -X POST -H "Content-type: text/csv" -H "Accept: text/turtle" --data-binary "@bar-sample.csv" "http://playground.fusepool.info:8300/?config=http://playground.fusepool.info:8181/ldp/tr/L"

(might take a while to return)

**Comment by danilogiacomi** [comment]
I've made some testing, but I wasn't able to understand where the process fails. 
With the pundit Transformer, being an asyncronous transformer using the User Interaction Request Registry, the final transformed document is never created (it used to be created untile somewhere in the middle of December)

**Comment by ktk** [comment]
@andreybratus just reminded me that we were talking about that once already. IIRC it was related to the size of the file, which means a small one worked but a bigger one not.

**Comment by ktk** [comment]
After talking to @retog, this must/might be related to timing. The transformer I did with the pipeline from Rupert takes quite a while to finish. With BatchRefine the effect was a problem for larger files, which probably take more time to finish. Small ones did show up.

**Comment by retog** [comment]
A preliminary finding: the proxy doesn't recognizes "text/turtle; charset=UTF-8" as RDF media type even if that media-type is correct.

**Comment by retog** [comment]
The reson that the transformation results do not show up in the T-LDPC:
```
HTTP/1.1 400 Bad Request
Date: Thu, 14 Jan 2016 15:43:04 GMT
Server: Apache Marmotta/3.4.0-SNAPSHOT (build 0)
ETag: W/"1452786182000"
Last-Modified: Thu, 14 Jan 2016 15:43:02 GMT
Link: <http://wiki.apache.org/marmotta/LDPImplementationReport/2014-09-16>; rel="http://www.w3.org/ns/ldp#constrainedBy"
Link: <http://www.w3.org/ns/ldp#Resource>; rel="type"
Link: <http://www.w3.org/ns/ldp#RDFSource>; rel="type"
Link: <http://www.w3.org/ns/ldp#Container>; rel="type"
Link: <http://www.w3.org/ns/ldp#BasicContainer>; rel="type"
Content-Type: text/turtle
Content-Length: 116
Connection: close

RDFParseException: '1921 (ca.)' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#gYear [line 4502]
write error to stdout
```

**Comment by retog** [comment]
No of course the question is where does the warning the proxy code logs gets swallowed....
