### ISSUE TITLE
Proxy appears not to forward client supplied Accept header 'as is' to a transformer

### ISSUE THREAD

**Issue by cblakeley** [fusepoolP3/p3-proxy#8]
If I post to the transforming proxy:

curl -i -H "Content-Type: text/csv" -H "Accept: application/rdf+xml"  -H "Slug: acco_150120_6.csv" -X POST --data-binary @accommodations_short_150120_1.csv -X POST http://sandbox.fusepool.info:8181/ldp/virtuoso-csv-transformer

the trace from the fusepool.openlinksw.com console shows
DB.DBA.ldgeneration: received format param: text/turtle
i.e. the originally supplied Accept header isn't received.

**Comment by retog** [comment]
The client submits as accept header what it would like to have as the response to the post request. If we would like to make the the accept header the transformer gets to be variable I think this should be a property of the transforming LDPC.
